### PR TITLE
support asynchronous autoloading in visual studio 2019

### LINKED ISSUE #29: In Visual Studio 2019, the editor says that it uses a deprecated API and then disables the extension
After you install this extension to Visual Studio 2019 it complaints that the extension uses a deprecated API and can only be loaded if you enable synchronous loading of extensions. By default, it disables the extension.

I don't know what particular part of the API has been deprectated by Microsoft, but to enable this with asynchronous extension loading, I think the fix would be to get the deprecated code updated.

### PR DESCRIPTION
**Pull request by abelbraaksma**
Fixes #29. 

@liulex, I hope you don't mind, this was your work in your fork, but I think it's excellent stuff that is useful for all users of this plugin.

I haven't tested it thoroughly, but from the looks of it it could well be what we've all been waiting for :).

@jakubbielawa this should make your excellent plugin compatible with VS 2019 and future versions, without requiring synchronous loading of all plugins just to enable this one. Perhaps you check it out and if it's stable, merge it in?

### CODE REVIEW

**Comment by liulex** [comment]
No problem. Glad to help. I've been using it for half a year and it works fine for me.

Thanks @jakubbielawa for your extension!

**Comment by jakubbielawa** [comment]
Hey guys, thanks for the pull request, I'll check it out tomorrow and let you know how it goes!

**Comment by jakubbielawa** [comment]
Looks good so far, I'll have more time for testing tomorrow and, if all goes well, will merge it then. Thanks.

**Review by jakubbielawa — APPROVED** [review]
Works fine

**Comment by abelbraaksma** [comment]
Great to hear that, tx for merging it in!

**Pull request merged**
