### PR TITLE
Added option UnifyFilesInSolutionOnSave and implementation.

### PR DESCRIPTION
**Pull request by waynebloss**
I believe these changes should suffice to solve issue #1.

However, I am unable to check my work since I do not have the older SDK on any computer at this time.

If you don't have time to test and release this, please let me know and I will spend some more time figuring out what else I need to setup in order to properly compile this extension for myself.

Thank you.

### CODE REVIEW

**Comment by waynebloss** [comment]
There is one problem that I can see with these changes.

The `UnifyFilesInSolutionOnSave` option depends on the `ForceDefaultLineEndingOnSave` option.

I can see 2 paths forward here:

1) Don't use the same option (`ForceDefaultLineEndingOnSave`) for both `SaveProjectItem` and `SaveSolution`. Make the new option the only one that gets used for `SaveSolution` (and rename it to `ForceDefaultLineEndingOnSaveSolution` or something like that).

2) Toggle the new option to `false` when the `ForceDefaultLineEndingOnSave` is set to `false` and put a note that it depends on the other option.

**Comment by waynebloss** [comment]
When I hit "Save All" I pretty much expect it to unify any files that I have open, but not every single file in my solution.

I'm not exactly sure if that is going to happen with this code.

If I don't hear from you, I'll eventually get around to setting up the proper dev environment to test this out. So, no big deal.

**Comment by jakubbielawa** [comment]
I've just tested this and unfortunately it does not work properly.

When I set the new setting to "False" and hit "Save All" nothing happens.

I would rather insert some condition in this [line](https://github.com/jakubbielawa/LineEndingsUnifier/blob/master/Line%20Endings%20Unifier/LineEndingsUnifierPackage.cs#L274), so when the given file is not open and the setting is set to false, line endings will not be unified in a project item representing the file.

Also, I think that your second idea regarding the settings depending on each other is the best and we should implement that.

I can change the required SDK to the newest version to make it possible to build the extension in VS 2015. I will do that.

Thanks.

**Comment by waynebloss** [comment]
@jakubbielawa Thanks for taking a look at it. I will leave this to you for now and maybe revisit this issue in the future if there is a real need. It's also very likely that the next version of VS will fix all bad behavior of VS regarding line endings and file encodings, since Microsoft is now working so hard to make cross platform developers happy.

The primary symptom is no longer an issue for me since I stopped setting any external editors as default. Instead, I setup a new hotkey for "ExternalCommand5", which opens the current file in Sublime Text.

(The reason I need *that* external editor is because everytime I paste something into VS' JSON editor, it reformats the whole section of the JSON, which is annoying. Hopefully they'll fix that in VS too.)

I'll just close this pull request for now since it's not in any shape to be pulled in. Thanks again.

**Comment by waynebloss** [comment]
Oh also...

> When I set the new setting to "False" and hit "Save All" nothing happens.

That's what I expected to happen. When I hit Save All, and no files are open, I just want to make sure my `*.sln` and `*.xxproj` files are saved.

If files *are* open, I would expect just those files to be unified.

**Pull request closed without merging**
